# Generated by Django 4.2.4 on 2023-08-11 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=200)),
                ('protcessor', models.CharField(default='', max_length=50)),
                ('ram', models.IntegerField(default=0)),
                ('ssd', models.IntegerField(default=0)),
                ('hdd', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('pc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_shop.pcmodel')),
            ],
        ),
    ]
